FROM golang:1.27-alpine as builder

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM golang:1.27-alpine

RUN apk add --no-cache postgresql-client

COPY --from=builder /go/bin/goose /usr/local/bin/goose

ENTRYPOINT ["goose"]
CMD ["up"]